Avoid unexpected NoMethodError
When access to document root "/" is recorded, statistic.command
is set to nil. It causes the following error when creating
record because create_record call command.arguments internally.

  NoMethodError: undefined method `arguments' for nil:NilClass